// MIDL data types: https://docs.microsoft.com/en-us/uwp/midl-3/intro


namespace StatisticsLibraryWRC
{
    [default_interface]
    runtimeclass FTest
    {
        FTest(Double sx1, Double sx2, Double n1, Double n2);
	
		FTest(Windows.Foundation.Collections.IVector<Double> x1, Windows.Foundation.Collections.IVector<Double> x2);

        Boolean Perform();

        Windows.Foundation.Collections.IMap<String, Double> Results();
    }
}
