// Statistics.idl

// MIDL data types: https://docs.microsoft.com/en-us/uwp/midl-3/intro

namespace StatisticsLibraryWRC
{
    [default_interface]
    runtimeclass Statistics
    {
        Statistics();

        Windows.Foundation.Collections.IMap<String, Double> DescriptiveStatistics(Windows.Foundation.Collections.IVector<Double> data);

        Windows.Foundation.Collections.IMap<String, Double> DescriptiveStatistics(Windows.Foundation.Collections.IVector<Double> data, Windows.Foundation.Collections.IVector<String> keys);

        Windows.Foundation.Collections.IMap<String, Double> LinearRegression(Windows.Foundation.Collections.IVector<Double> xs, Windows.Foundation.Collections.IVector<Double> ys);
    }
}
